# Generated by Django 5.1.4 on 2024-12-28 13:49

import core.services.s3_service

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_carmodel_photo_carphotomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=core.services.s3_service.CarStorage(), upload_to='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='cars.carmodel')),
            ],
            options={
                'db_table': 'car_images',
            },
        ),
    ]
