# Generated by Django 5.1.4 on 2024-12-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carimagesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarPhotoModel',
        ),
    ]
