# Generated by Django 5.1.4 on 2024-12-27 12:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.profilemodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*\\d)(?=.*[`~!@#$%^&*()_\\-+=\\\\|\\[\\]{};:\\\'"\\/\\?\\.>,<])[a-zA-Z\\d`~!@#$%^&*()_\\-+=\\\\|\\[\\]{};:\\\'"\\/\\?\\.>,<]{8,30}$', ['min 1 lowercase', 'min 1 uppercase', 'min 1 digit', 'min 1 special character', 'length 8-30 ch'])]),
        ),
    ]
