# Generated by Django 5.1.4 on 2024-12-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_options_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='age',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='birth_day',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
