# Generated by Django 5.1.4 on 2025-01-04 19:46

import phonenumber_field.modelfields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profilemodel_age_profilemodel_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default="380685765809", max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
