# Generated by Django 5.1.4 on 2025-01-04 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
        ('users', '0006_profilemodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.TextField()),
                ('specialization', models.ManyToManyField(to='mentorship.specializationmodel')),
                ('technology_stack', models.ManyToManyField(to='mentorship.technologystackmodel')),
            ],
            options={
                'db_table': 'mentor_profile',
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='mentor_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.mentorprofilemodel'),
        ),
    ]
