# Generated by Django 5.1.5 on 2025-01-16 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_taskmodel_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(max_length=30)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room', to='task.taskmodel')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
