# Generated by Django 5.1.5 on 2025-01-16 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_roomsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsmodel',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='roomsmodel',
            name='users',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='task.roomsmodel'),
        ),
    ]
