# Generated by Django 5.1.5 on 2025-01-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_roomsmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomsmodel',
            old_name='user',
            new_name='users',
        ),
    ]
