# Generated by Django 5.1.5 on 2025-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_remove_roomsmodel_users_roomsmodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('ToDo', 'Todo'), ('InProgress', 'Inprogress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
