# Generated by Django 5.1.5 on 2025-01-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_taskmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='room',
        ),
        migrations.DeleteModel(
            name='RoomsModel',
        ),
    ]
