# Generated by Django 5.1.4 on 2025-01-04 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorship', '0001_initial'),
        ('users', '0007_mentorprofilemodel_usermodel_mentor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringservicemodel',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.mentorprofilemodel'),
        ),
        migrations.AddField(
            model_name='mentorshipformatmodel',
            name='mentoring_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_formats', to='mentorship.mentoringservicemodel'),
        ),
    ]
