# Generated by Django 5.1.4 on 2025-01-04 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoringservicemodel',
            name='mentor',
        ),
        migrations.AddField(
            model_name='mentoringservicemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_service', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
